🚀 Upgrade to .Net 6.0
Homely/Homely.AspNetCore.Mvc.Helpers pull request #42
Opened 2021-11-24 03:29 UTC by PureKrome

YAY!

Also includes some specific stuff like the new c# 8/9/10 features, like nullable enabled, etc.

2021-11-26 05:41 UTC, PureKrome commented
sigh. tests busted.

2021-11-26 08:14 UTC, PureKrome commented
Good to go, again.

2021-11-28 22:02 UTC, RPM1984 commented
Do we know why coverage has dropped 11%?

2021-11-28 22:36 UTC, PureKrome commented
Yes - found it hard to test some extensions helper class

2021-11-28 23:25 UTC, RPM1984 requested changes

2021-11-28 23:25 UTC, RPM1984 commented on src/Homely.AspNetCore.Mvc.Helpers/Models/OpenApiSettings.cs
> +    public class IsExternalInit { }
is this still req'd?

2021-11-28 23:25 UTC, RPM1984 commented on tests/TestWebApplication/TestWebApplication.csproj
> +  </ItemGroup>-->
pls remove

2021-11-29 00:50 UTC, PureKrome commented on src/Homely.AspNetCore.Mvc.Helpers/Models/OpenApiSettings.cs
> +    public class IsExternalInit { }
🔧

2021-11-29 00:50 UTC, PureKrome commented on tests/TestWebApplication/TestWebApplication.csproj
> +  </ItemGroup>-->
🔧

2021-11-29 00:52 UTC, RPM1984 approved these changes

2021-11-29 00:53 UTC, merged